services:
  confetti:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    hostname: confetti
    ports:
      - "8080:33046"
    environment:
      - CORS_ORIGIN=http://127.0.0.1 # set to your domain
      - BGP_ENABLED=true # allow bgp queryies
      - PINGTRACE_ENABLED=false # allow ping/trace/mtr
